modLoader="javafml"
loaderVersion="[45,)"
license="Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License"
[[mods]]
modId="expanded_tooltips"
version="${file.jarVersion}"
displayName="Expanded Tooltips"
displayURL="https://www.curseforge.com/minecraft/mc-mods/expanded-tooltips-forge"
logoFile="icon.png"
credits=""
authors="Uraneptus, Rolly"
description='''
A simple mod allowing for custom item descriptions.
'''
[[dependencies.expanded_tooltips]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.expanded_tooltips]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
