modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"
[[mods]]
modId="expanded_tooltips"
version="${file.jarVersion}"
displayName="Expanded Tooltips"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="icon.png"
credits=""
authors="Uraneptus, Rolly"
description='''
A simple mod allowing for custom item descriptions.
'''
[[dependencies.expanded_tooltips]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.expanded_tooltips]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
